name: 'setup'

on:
  workflow_dispatch:
  push:
        branches:
            - 'main'  # or your default branch
        paths:
            - 'challenges/**'
  pull_request:
        branches:
            - '**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
        run:
            # working-directory: ./challenges/challenge4
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6  # Specify the Terraform version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init
      # replace above file with terraform init -backend-config="bucket=exammple-bucket" -backend-config="key=examplefile.tfstate"
      # replace bucket and file with your info

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve